export const metadata = {
  title: "Disclaimer — FINRLX",
};

export default function DisclaimerPage() {
  return (
    <article className="mx-auto max-w-2xl space-y-4 py-8 text-ink-2">
      <h1 className="text-2xl font-semibold text-ink">Disclaimer</h1>
      <p className="text-sm text-ink-3">Last updated: 2026-05-20</p>

      <h2 className="pt-4 text-lg font-semibold">Not investment advice</h2>
      <p>
        FINRLX is a decision-support research tool. Nothing displayed in this
        application — including but not limited to scores, weights,
        recommendations, confidences, scenarios, paper-portfolio activity, and
        replay output — constitutes investment advice, a solicitation to buy or
        sell any security, or a recommendation tailored to your personal
        financial situation. We are not a broker-dealer, registered investment
        adviser, or financial planner.
      </p>

      <h2 className="pt-4 text-lg font-semibold">Models and historical data</h2>
      <p>
        Output is generated by quantitative models applied to historical market
        data. Models can be wrong. Historical data does not predict future
        results. We make no representation that any output will be profitable
        or that it will avoid losses.
      </p>

      <h2 className="pt-4 text-lg font-semibold">Beta status</h2>
      <p>
        FINRLX is currently in private beta. Features may change, break, or be
        removed without notice. Data shown is for illustrative and educational
        purposes during the beta period.
      </p>

      <h2 className="pt-4 text-lg font-semibold">Your responsibility</h2>
      <p>
        You are solely responsible for any investment decisions you make. Always
        consult a qualified, licensed financial professional in your
        jurisdiction before acting on any information you see here. If you do
        not understand a security or strategy, do not transact in it.
      </p>
    </article>
  );
}
