// Integrations — data
const IG_CATEGORIES = [
  { id: "all",     label: "All" },
  { id: "market",  label: "Market data" },
  { id: "alt",     label: "Alt data" },
  { id: "fund",    label: "Fundamentals" },
  { id: "news",    label: "News & sentiment" },
  { id: "oms",     label: "OMS / execution" },
  { id: "ware",    label: "Warehouse" },
  { id: "comms",   label: "Comms" },
  { id: "sso",     label: "Identity" },
];

// Connected integrations — richer than Ops' feed list
const IG_ACTIVE = [
  {
    id: "bloomberg",
    name: "Bloomberg Terminal",
    logo: "bloomberg", mark: "B",
    cat: "Market data",
    catId: "market",
    desc: "Real-time prices, fundamentals, reference data. SAPI feed handler.",
    status: "ok",
    lag: "12ms", coverage: "100%", slo: "99.9%",
    connected: "Dec 14, 2024", connectedBy: "Rivka Shoval",
    entitlement: "B-PIPE Premium · 47 fields",
    lastSync: "just now",
    cost: "$2,340/mo",
    usedBy: ["5 engines", "Policy editor", "Universe builder"],
    usedByCt: 12,
    schema: [
      { f: "last_price",   t: "float",    sample: "182.63" },
      { f: "volume",       t: "int64",    sample: "48293100" },
      { f: "market_cap",   t: "float",    sample: "4.56T" },
      { f: "bid_ask",      t: "tuple",    sample: "(182.60, 182.65)" },
      { f: "pe_ratio",     t: "float",    sample: "74.2" },
      { f: "bid_size",     t: "int32",    sample: "1200" },
    ],
    creds: { endpoint: "sapi.bloomberg.com:8194", authMode: "UUID + AppName", accountId: "rivka-capital-prod" },
    spark: Array.from({length:24}, () => 0.92 + Math.random()*0.07),
  },
  {
    id: "refinitiv",
    name: "Refinitiv Eikon",
    logo: "refinitiv", mark: "R",
    cat: "Market data",
    catId: "market",
    desc: "Price, corporate actions, deep history. Secondary price source for arbitration.",
    status: "ok",
    lag: "38ms", coverage: "99.6%", slo: "99.5%",
    connected: "Dec 14, 2024", connectedBy: "Rivka Shoval",
    entitlement: "Elektron · L1 prices · 28 countries",
    lastSync: "just now",
    cost: "$1,850/mo",
    usedBy: ["3 engines", "Arbitration"],
    usedByCt: 7,
    schema: [
      { f: "trade_price",  t: "float",   sample: "182.61" },
      { f: "trade_size",   t: "int32",   sample: "100" },
      { f: "corp_action",  t: "string",  sample: "div_0.24_2026-04-28" },
    ],
    creds: { endpoint: "emea-apne1.edp.thomsonreuters.com", authMode: "OAuth2 machine", accountId: "rivka-9842" },
    spark: Array.from({length:24}, () => 0.9 + Math.random()*0.08),
  },
  {
    id: "cboe",
    name: "CBOE Options Flow",
    logo: "cboe", mark: "C",
    cat: "Market data",
    catId: "market",
    desc: "Options volume, OI, flow intelligence. Feeds flow/options engine.",
    status: "degraded",
    lag: "14m", coverage: "72%", slo: "85.2%",
    issue: "Latency above 10s threshold since 14m ago — auto down-weighted.",
    connected: "Jan 8, 2025", connectedBy: "Hadar Levi",
    entitlement: "CBOE LiveVol · US eq options",
    lastSync: "14m ago",
    cost: "$420/mo",
    usedBy: ["Flow engine"],
    usedByCt: 2,
    schema: [
      { f: "call_volume",  t: "int32",   sample: "48210" },
      { f: "put_volume",   t: "int32",   sample: "32100" },
      { f: "pc_ratio",     t: "float",   sample: "0.67" },
      { f: "iv_atm",       t: "float",   sample: "0.42" },
    ],
    creds: { endpoint: "api.livevol.com/v3", authMode: "API key", accountId: "rkc-prod-002" },
    spark: [0.95,0.94,0.96,0.95,0.93,0.94,0.92,0.90,0.88,0.85,0.78,0.72,0.68,0.65,0.62,0.60,0.58,0.56,0.54,0.52,0.50,0.48,0.46,0.44].map((v,i)=>v),
    sparkKind: "down",
  },
  {
    id: "factset",
    name: "FactSet",
    logo: "factset", mark: "F",
    cat: "Fundamentals",
    catId: "fund",
    desc: "Earnings, estimates, ownership data. Feeds quality engine.",
    status: "ok",
    lag: "3s", coverage: "99.4%", slo: "99.2%",
    connected: "Dec 14, 2024", connectedBy: "Rivka Shoval",
    entitlement: "FDS Core + Ownership",
    lastSync: "47s ago",
    cost: "$1,100/mo",
    usedBy: ["Quality engine", "Overview"],
    usedByCt: 5,
    schema: [
      { f: "eps_estimate", t: "float",  sample: "3.89" },
      { f: "eps_actual",   t: "float",  sample: "3.92" },
      { f: "surprise",     t: "float",  sample: "+0.77%" },
      { f: "roic",         t: "float",  sample: "0.224" },
    ],
    creds: { endpoint: "api.factset.com", authMode: "OAuth2", accountId: "rivka-cap-01" },
    spark: Array.from({length:24}, () => 0.92 + Math.random()*0.07),
  },
  {
    id: "reuters",
    name: "Reuters News Intel",
    logo: "reuters", mark: "R",
    cat: "News & sentiment",
    catId: "news",
    desc: "Machine-readable news, entity linking, Reuters NewsBoost tags.",
    status: "ok",
    lag: "0s", coverage: "99.8%", slo: "99.7%",
    connected: "Jan 3, 2025", connectedBy: "Rivka Shoval",
    entitlement: "MRN Stories + Entities",
    lastSync: "just now",
    cost: "$680/mo",
    usedBy: ["News engine", "Alerts"],
    usedByCt: 4,
    schema: [
      { f: "headline",     t: "string",  sample: "\"NVDA beats Q1 estimates…\"" },
      { f: "entities",     t: "list",    sample: "[NVDA, TSM, AMD]" },
      { f: "sentiment",    t: "float",   sample: "+0.78" },
      { f: "novelty",      t: "float",   sample: "0.44" },
    ],
    creds: { endpoint: "mrn-a.reuters.com", authMode: "cert+pwd", accountId: "RKC-MRN-01" },
    spark: Array.from({length:24}, () => 0.94 + Math.random()*0.05),
  },
  {
    id: "ravenpack",
    name: "RavenPack News Analytics",
    logo: "ravenpack", mark: "RP",
    cat: "Alt data",
    catId: "alt",
    desc: "Aggregated news sentiment with entity-level scores.",
    status: "paused",
    lag: "—", coverage: "—", slo: "—",
    pausedReason: "Paused by Hadar Levi 3d ago — pending contract renewal.",
    connected: "Feb 20, 2025", connectedBy: "Hadar Levi",
    entitlement: "Edge · US equities · ESG overlay",
    lastSync: "3d ago",
    cost: "$2,200/mo",
    usedBy: ["(disconnected)"],
    usedByCt: 0,
    schema: [
      { f: "ess",          t: "float",   sample: "78.2" },
      { f: "buzz",         t: "float",   sample: "1.4" },
      { f: "relevance",    t: "int",     sample: "95" },
    ],
    creds: { endpoint: "api.ravenpack.com/1.0", authMode: "API key", accountId: "rkc-ravenpack" },
    spark: Array.from({length:24}, () => 0.4),
    sparkKind: "out",
  },
  {
    id: "ms-teams",
    name: "Microsoft Teams",
    logo: "ms", mark: "M",
    cat: "Comms",
    catId: "comms",
    desc: "Decision publication notifications, mentions, at-risk alerts.",
    status: "ok",
    lag: "420ms", coverage: "100%", slo: "99.9%",
    connected: "Dec 15, 2024", connectedBy: "Rivka Shoval",
    entitlement: "Bot + 3 channels",
    lastSync: "2m ago",
    cost: "Included",
    usedBy: ["Alerts", "Publication flow"],
    usedByCt: 3,
    schema: [
      { f: "channel",      t: "string",  sample: "#decisions-live" },
      { f: "mention",      t: "list",    sample: "[@hadar, @rivka]" },
    ],
    creds: { endpoint: "graph.microsoft.com/v1.0", authMode: "OAuth2 app", accountId: "tenant-rkc" },
    spark: Array.from({length:24}, () => 0.95 + Math.random()*0.04),
  },
  {
    id: "okta",
    name: "Okta Identity Cloud",
    logo: "okta", mark: "O",
    cat: "Identity",
    catId: "sso",
    desc: "SSO + SCIM provisioning for all workspace members.",
    status: "ok",
    lag: "—", coverage: "—", slo: "99.99%",
    connected: "Dec 14, 2024", connectedBy: "Rivka Shoval",
    entitlement: "SAML 2.0 + SCIM v2",
    lastSync: "14m ago",
    cost: "Included",
    usedBy: ["All members"],
    usedByCt: 6,
    schema: [
      { f: "user_email",   t: "string",  sample: "rivka@rivkacap.com" },
      { f: "groups",       t: "list",    sample: "[Admins, Engineering]" },
      { f: "mfa_enrolled", t: "bool",    sample: "true" },
    ],
    creds: { endpoint: "rivka-cap.okta.com/api/v1", authMode: "OAuth2 + SAML", accountId: "rkc-okta" },
    spark: Array.from({length:24}, () => 0.99),
  },
  {
    id: "snowflake",
    name: "Snowflake",
    logo: "snowflake", mark: "S",
    cat: "Warehouse",
    catId: "ware",
    desc: "Historical feature store. Dumps daily for backtests and replay.",
    status: "ok",
    lag: "1.2s", coverage: "100%", slo: "99.8%",
    connected: "Jan 22, 2025", connectedBy: "Noam Katz",
    entitlement: "X-Large warehouse · 2TB storage",
    lastSync: "18m ago",
    cost: "$890/mo",
    usedBy: ["Backtests", "Replay", "Universe"],
    usedByCt: 8,
    schema: [
      { f: "ticker",       t: "string",  sample: "NVDA" },
      { f: "dt",           t: "date",    sample: "2026-04-23" },
      { f: "features",     t: "vector",  sample: "float[128]" },
    ],
    creds: { endpoint: "rkc.eu-central-1.snowflakecomputing.com", authMode: "key-pair", accountId: "RKC_PROD" },
    spark: Array.from({length:24}, () => 0.98),
  },
];

// Catalog — available but not connected
const IG_CATALOG = [
  { id: "polygon", name: "Polygon.io", mark: "P", logo: "polygon", cat: "Market data", catId: "market",
    desc: "US equities, options, forex, crypto. REST + WebSocket.", tag: "$399/mo", note: "Popular among systematic quants." },
  { id: "sp", name: "S&P Capital IQ", mark: "S&P", logo: "sp", cat: "Fundamentals", catId: "fund",
    desc: "Deep fundamental data, credit ratings, M&A intel.", tag: "Contact sales", note: "Enterprise" },
  { id: "truvalue", name: "Truvalue Labs ESG", mark: "TV", logo: "truvalue", cat: "Alt data", catId: "alt",
    desc: "Real-time ESG signals from 100k+ public sources.", tag: "$4,800/mo", note: "ESG overlay for sustainability mandates." },
  { id: "quandl", name: "Quandl (Nasdaq Data Link)", mark: "Q", logo: "quandl", cat: "Alt data", catId: "alt",
    desc: "Alternative datasets, satellite, credit card, consumer.", tag: "Per dataset" },
  { id: "slack", name: "Slack", mark: "S", logo: "slack", cat: "Comms", catId: "comms",
    desc: "Decision alerts, at-risk notifications, mentions.", tag: "Included" },
  { id: "pagerduty", name: "PagerDuty", mark: "PD", logo: "pagerduty", cat: "Comms", catId: "comms",
    desc: "Route sev-1 incidents to on-call rotations.", tag: "Included" },
  { id: "databricks", name: "Databricks", mark: "DB", logo: "databricks", cat: "Warehouse", catId: "ware",
    desc: "Alternative to Snowflake. Unity Catalog support.", tag: "BYO cluster" },
  { id: "oms-fix", name: "FIX 4.4 OMS gateway", mark: "FIX", logo: "generic", cat: "OMS / execution", catId: "oms",
    desc: "Connect any OMS/EMS speaking FIX — IB, Fidessa, Charles River.", tag: "Included", note: "Sandbox + prod endpoints." },
  { id: "oms-ibkr", name: "Interactive Brokers", mark: "IB", logo: "generic", cat: "OMS / execution", catId: "oms",
    desc: "Direct TWS API integration for smaller shops.", tag: "Included" },
];

Object.assign(window, { IG_CATEGORIES, IG_ACTIVE, IG_CATALOG });
