// Policy editor — data
// 6 categories, ~14 policies. Each policy has rule conditions, action,
// and simulated "impact" counts against current live recommendations.

const POLICY_CATEGORIES = [
  { key: "position",  label: "Position limits",  icon: "risk",      count: 3 },
  { key: "exposure",  label: "Exposure caps",    icon: "portfolio", count: 3 },
  { key: "sector",    label: "Sector rules",     icon: "universe",  count: 2 },
  { key: "approval",  label: "Approval flows",   icon: "ops",       count: 2 },
  { key: "stoploss",  label: "Stop-loss",        icon: "breach",    count: 2 },
  { key: "regime",    label: "Regime gates",     icon: "compare",   count: 2 },
];

const POLICIES = [
  {
    id: "pol-pos-max",
    cat: "position",
    name: "Max single-name weight",
    desc: "Cap any single position at a fixed share of portfolio NAV.",
    on: true,
    rule: [{ field: "position.weight", op: ">", val: "6%" }],
    action: { kind: "block", text: "Block publication. Suggest a trim recommendation instead." },
    impact: {
      blocked: 2, warned: 1,
      hits: [
        { tk: "NVDA",  desc: "proposed 7.4% weight", pol: "> 6%", kind: "block" },
        { tk: "MSFT",  desc: "proposed 6.2% weight", pol: "> 6%", kind: "block" },
        { tk: "AAPL",  desc: "at 5.8% — 0.2% to limit", pol: "warn-proximity", kind: "warn" },
      ]
    },
    author: "Rachel Moy",
    updated: "Apr 18, 2026",
  },
  {
    id: "pol-pos-min",
    cat: "position",
    name: "Minimum meaningful size",
    desc: "Reject publications below a size that materially affects performance.",
    on: true,
    rule: [{ field: "position.weight", op: "<", val: "0.5%" }],
    action: { kind: "warn", text: "Flag for review — position may be too small to justify research cost." },
    impact: { blocked: 0, warned: 3, hits: [] },
    author: "Tanvi Nair",
    updated: "Mar 29, 2026",
  },
  {
    id: "pol-pos-leverage",
    cat: "position",
    name: "No direct leverage",
    desc: "Disallow recommendations using leveraged instruments.",
    on: false,
    rule: [
      { field: "instrument.type",     op: "in", val: "['2x_ETF','3x_ETF','futures']" },
      { field: "position.leverage",   op: ">", val: "1.0x", and: true },
    ],
    action: { kind: "block", text: "Block publication. No override — firm-wide rule." },
    impact: { blocked: 0, warned: 0, hits: [] },
    author: "Compliance",
    updated: "Feb 04, 2026",
  },
  {
    id: "pol-exp-sector",
    cat: "exposure",
    name: "Sector exposure cap · Tech",
    desc: "Limit aggregate exposure to the Technology sector.",
    on: true,
    rule: [{ field: "portfolio.sector('Technology').weight", op: ">", val: "35%" }],
    action: { kind: "block", text: "Block any new tech publication that would push aggregate over 35%." },
    impact: {
      blocked: 3, warned: 1,
      hits: [
        { tk: "NVDA",  desc: "would push tech to 37.2%", pol: "Tech > 35%", kind: "block" },
        { tk: "AVGO",  desc: "would push tech to 36.4%", pol: "Tech > 35%", kind: "block" },
        { tk: "ANET",  desc: "would push tech to 35.8%", pol: "Tech > 35%", kind: "block" },
        { tk: "MSFT",  desc: "within 2% of cap",         pol: "Tech > 33%",  kind: "warn" },
      ]
    },
    author: "Rachel Moy",
    updated: "Apr 21, 2026",
  },
  {
    id: "pol-exp-factor",
    cat: "exposure",
    name: "Factor concentration · Momentum",
    desc: "Cap net momentum-factor exposure to avoid crowded-trade risk.",
    on: true,
    rule: [{ field: "portfolio.factor('momentum').beta", op: ">", val: "0.8" }],
    action: { kind: "warn", text: "Warn before publication; escalate above 1.0." },
    impact: { blocked: 0, warned: 2, hits: [] },
    author: "Rachel Moy",
    updated: "Apr 09, 2026",
  },
  {
    id: "pol-exp-country",
    cat: "exposure",
    name: "Non-US exposure floor",
    desc: "Require at least some international diversification.",
    on: false,
    rule: [{ field: "portfolio.country('non-US').weight", op: "<", val: "10%" }],
    action: { kind: "warn", text: "Flag portfolio review — below international diversification floor." },
    impact: { blocked: 0, warned: 0, hits: [] },
    author: "Rachel Moy",
    updated: "Jan 14, 2026",
  },
  {
    id: "pol-sec-forbid",
    cat: "sector",
    name: "Forbidden sectors",
    desc: "Never recommend — firm-wide exclusion list.",
    on: true,
    rule: [{ field: "ticker.sector", op: "in", val: "['Tobacco','Defense-Controversial']" }],
    action: { kind: "block", text: "Silent block. Universe filter removes tickers before ranking." },
    impact: { blocked: 0, warned: 0, hits: [] },
    author: "Compliance",
    updated: "Nov 02, 2025",
  },
  {
    id: "pol-sec-esg",
    cat: "sector",
    name: "ESG minimum score",
    desc: "Require minimum MSCI ESG rating on held positions.",
    on: true,
    rule: [{ field: "ticker.esg.rating", op: "<", val: "BB" }],
    action: { kind: "warn", text: "Flag for ESG review before publication." },
    impact: {
      blocked: 0, warned: 1,
      hits: [
        { tk: "XOM",  desc: "rating BB, within band", pol: "< BB", kind: "warn" },
      ]
    },
    author: "Rachel Moy",
    updated: "Mar 02, 2026",
  },
  {
    id: "pol-apr-twomiddle",
    cat: "approval",
    name: "Dual approval · size > 3%",
    desc: "Any publication sized above 3% NAV requires two sign-offs.",
    on: true,
    rule: [{ field: "position.weight", op: ">", val: "3%" }],
    action: { kind: "allow", text: "Allow but require 2 approvers (PM + Risk)." },
    impact: {
      blocked: 0, warned: 0,
      hits: [
        { tk: "NVDA",  desc: "requires 2 approvers", pol: "> 3%", kind: "warn" },
        { tk: "MSFT",  desc: "requires 2 approvers", pol: "> 3%", kind: "warn" },
      ]
    },
    author: "Compliance",
    updated: "Feb 18, 2026",
  },
  {
    id: "pol-apr-overnight",
    cat: "approval",
    name: "No overnight autopublish",
    desc: "Require human approval outside trading hours.",
    on: true,
    rule: [{ field: "time.market_open", op: "=", val: "false" }],
    action: { kind: "warn", text: "Queue for human review — no autopublish after 4pm ET." },
    impact: { blocked: 0, warned: 0, hits: [] },
    author: "Ops",
    updated: "Feb 01, 2026",
  },
  {
    id: "pol-sl-hard",
    cat: "stoploss",
    name: "Hard stop · −8%",
    desc: "Auto-generate a SELL recommendation if unrealized loss breaches 8%.",
    on: true,
    rule: [{ field: "position.pnl_pct", op: "<", val: "-8%" }],
    action: { kind: "block", text: "Auto-trigger sell recommendation. Requires PM acknowledge." },
    impact: { blocked: 0, warned: 0, hits: [] },
    author: "Compliance",
    updated: "Nov 02, 2025",
  },
  {
    id: "pol-sl-trail",
    cat: "stoploss",
    name: "Trailing stop · 4% from peak",
    desc: "Recommend trim when position gives back 4% of peak gain.",
    on: false,
    rule: [{ field: "position.drawdown_from_peak", op: ">", val: "4%" }],
    action: { kind: "warn", text: "Emit trim recommendation at 50% of size." },
    impact: { blocked: 0, warned: 0, hits: [] },
    author: "Rachel Moy",
    updated: "Apr 02, 2026 · draft",
    draft: true,
  },
  {
    id: "pol-reg-riskoff",
    cat: "regime",
    name: "Risk-off gate · high-beta",
    desc: "In risk-off regimes, block new long recommendations with β > 1.3.",
    on: true,
    rule: [
      { field: "regime.current", op: "=", val: "'risk-off'" },
      { field: "ticker.beta_3m", op: ">", val: "1.3", and: true },
    ],
    action: { kind: "block", text: "Block publication with reason 'regime gate'." },
    impact: { blocked: 0, warned: 0, hits: [] },
    author: "Rachel Moy",
    updated: "Mar 15, 2026",
  },
  {
    id: "pol-reg-crowding",
    cat: "regime",
    name: "Crowding guard",
    desc: "In late-cycle regimes, warn on positions in top-decile crowded trades.",
    on: true,
    rule: [
      { field: "regime.current", op: "=", val: "'late-cycle'" },
      { field: "ticker.crowding_rank", op: ">", val: "90", and: true },
    ],
    action: { kind: "warn", text: "Require written rationale if published." },
    impact: {
      blocked: 0, warned: 1,
      hits: [
        { tk: "NVDA", desc: "crowding rank 97", pol: "crowded in late-cycle", kind: "warn" },
      ]
    },
    author: "Rachel Moy",
    updated: "Apr 22, 2026",
  },
];

Object.assign(window, { POLICY_CATEGORIES, POLICIES });
