"""Phase 18.5 — TickerInsights model.

Cross-document analysis artifact: one row per (ticker, generation
event). Each row is the LLM's structured response to "synthesize a
trajectory + latest-quarter delta across these N filings" — separate
from `document_analyses` because:

  - It's a CROSS-DOCUMENT artifact (covers multiple filings), not
    tied to one ResearchDocument. Forcing it into document_analyses
    would mean either picking a "primary" document arbitrarily or
    creating a many-to-many join table that adds complexity for no
    real benefit.

  - It has different freshness semantics. Per-document analyses are
    immutable history of operator questions; insights have a TTL
    (the FE treats anything >7 days old as stale and offers to
    regenerate). Keeping them separate avoids polluting the
    per-document history with auto-generated noise.

The FE flow:
  - GET /research/{ticker}/insights → returns the most recent row
    (or null if none generated yet). The FE checks generated_at and
    shows "Stale (N days old) — refresh?" when needed.
  - POST /research/{ticker}/insights → triggers a new generation
    via the gemini chain and persists the result.

We keep history (don't UPDATE in place) so we can audit how the
analysis evolved as new filings were ingested.
"""
from datetime import datetime

from sqlalchemy import JSON, DateTime, Float, Index, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base
from app.models.base import gen_uuid


class TickerInsights(Base):
    __tablename__ = "ticker_insights"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=gen_uuid)

    # Always upper-cased on insert. The composite index below makes
    # "most recent insights for ticker X" a clean index scan.
    ticker: Mapped[str] = mapped_column(String(16), nullable=False)

    # The LLM's narrative (latest-quarter delta, risk-factor changes,
    # what-to-watch sections). The trajectory itself lives in the
    # structured `metrics` column below — the FE renders it as a
    # chart, not inside this text.
    summary_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Phase 18.6.1 — Structured metrics extracted from the LLM's
    # JSON block. Shape: {"metrics": [{name, unit, quarters:
    # [{period_end, label, value}, ...]}, ...]}. The FE renders these
    # as a multi-series line chart matching PriceChartCard's style.
    # Nullable so backwards-compat (older rows have no chart data)
    # and to handle the rare case where the LLM emits no parseable
    # JSON block.
    metrics: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # List of SEC accession numbers this analysis covered. Stored as
    # JSON so the FE can show "based on Q1 FY27 + Q4 FY26 + ..." with
    # links back to each filing. JSON works on both Postgres and
    # SQLite via SQLAlchemy's JSON type (TEXT serialization underneath).
    quarters_covered: Mapped[list[str]] = mapped_column(
        JSON, nullable=False, default=list
    )

    # LLM provenance — verbatim from the provider's response object.
    # Matches the naming used in DocumentAnalysis for FE consistency.
    provider: Mapped[str] = mapped_column(String(40), nullable=False)
    model: Mapped[str] = mapped_column(String(120), nullable=False, default="")
    input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cost_estimate_usd: Mapped[float | None] = mapped_column(Float, nullable=True)

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Operator who triggered the generation. Insights are SHARED BY
    # TICKER (anyone signed-in can read the latest); the email is for
    # audit + "regenerated by X" UI labels.
    generated_by_email: Mapped[str] = mapped_column(String(320), nullable=False)

    __table_args__ = (
        # Composite (ticker, generated_at) supports the dominant
        # query pattern: "latest insights for this ticker". The
        # planner uses the leading column for the WHERE filter and
        # the second for the ORDER BY.
        Index("ix_ticker_insights_ticker_generated_at", "ticker", "generated_at"),
    )
