"""Phase 18.5 — TickerInsights model contract tests.

What these pin:
  - Row inserts with all required fields populated.
  - `quarters_covered` JSON column round-trips list[str] correctly
    (Postgres native + SQLite TEXT serialization both work).
  - Composite (ticker, generated_at) index supports the "most recent
    for ticker" query pattern.
  - Multiple insights per ticker coexist (history is kept, not
    overwritten in place).
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

import pytest
from sqlalchemy import select

from app.models.ticker_insights import TickerInsights


@pytest.fixture(autouse=True)
async def _clean_ticker_insights():
    """Wipe rows between tests since the in-memory DB is session-scoped."""
    from tests.conftest import test_session_factory
    from sqlalchemy import delete

    async with test_session_factory() as db:
        await db.execute(delete(TickerInsights))
        await db.commit()
    yield


@pytest.mark.asyncio
async def test_insert_and_read_back_round_trip():
    from tests.conftest import test_session_factory

    accessions = [
        "0001045810-26-000012",
        "0001045810-25-000045",
        "0001045810-25-000031",
    ]
    async with test_session_factory() as db:
        row = TickerInsights(
            ticker="NVDA",
            summary_text="Revenue trajectory: $35B → $30B → $28B (decelerating). Latest quarter: gross margin compressed 200 bps.",
            quarters_covered=accessions,
            provider="gemini",
            model="gemini-2.5-flash",
            input_tokens=120000,
            output_tokens=800,
            cost_estimate_usd=0.0094,
            generated_by_email="op@finrlx.local",
        )
        db.add(row)
        await db.commit()
        saved_id = row.id

    async with test_session_factory() as db:
        saved = (
            await db.execute(select(TickerInsights).where(TickerInsights.id == saved_id))
        ).scalar_one()

    assert saved.ticker == "NVDA"
    assert "Revenue trajectory" in saved.summary_text
    assert saved.quarters_covered == accessions
    assert saved.provider == "gemini"
    assert saved.model == "gemini-2.5-flash"
    assert saved.input_tokens == 120000
    assert saved.output_tokens == 800
    assert saved.cost_estimate_usd == pytest.approx(0.0094)
    assert saved.generated_by_email == "op@finrlx.local"
    assert saved.generated_at is not None


@pytest.mark.asyncio
async def test_multiple_insights_per_ticker_kept_as_history():
    """Insights are append-only history. Two rows for NVDA coexist
    so the FE can show 'regenerated by X' audit trail later if
    desired."""
    from tests.conftest import test_session_factory

    async with test_session_factory() as db:
        db.add(
            TickerInsights(
                ticker="NVDA",
                summary_text="First run.",
                quarters_covered=["acc-1"],
                provider="gemini",
                model="gemini-2.5-flash",
                generated_by_email="op@finrlx.local",
            )
        )
        db.add(
            TickerInsights(
                ticker="NVDA",
                summary_text="Second run (regenerated).",
                quarters_covered=["acc-1", "acc-2"],
                provider="gemini",
                model="gemini-2.5-flash",
                generated_by_email="op@finrlx.local",
            )
        )
        await db.commit()

    async with test_session_factory() as db:
        rows = (
            await db.execute(select(TickerInsights).where(TickerInsights.ticker == "NVDA"))
        ).scalars().all()

    assert len(rows) == 2
    # Both versions of the summary text are present — the second did
    # NOT overwrite the first.
    summaries = {r.summary_text for r in rows}
    assert "First run." in summaries
    assert "Second run (regenerated)." in summaries


@pytest.mark.asyncio
async def test_query_most_recent_for_ticker_returns_correct_row():
    """The composite index supports "latest insights for ticker X".
    SQLAlchemy ORDER BY DESC LIMIT 1 picks out the newest row."""
    from tests.conftest import test_session_factory

    older_time = datetime.now(timezone.utc) - timedelta(days=10)
    newer_time = datetime.now(timezone.utc) - timedelta(hours=1)

    async with test_session_factory() as db:
        db.add(
            TickerInsights(
                ticker="MSFT",
                summary_text="OLDER",
                quarters_covered=[],
                provider="gemini",
                model="gemini-2.5-flash",
                generated_at=older_time,
                generated_by_email="op@finrlx.local",
            )
        )
        db.add(
            TickerInsights(
                ticker="MSFT",
                summary_text="NEWER",
                quarters_covered=[],
                provider="gemini",
                model="gemini-2.5-flash",
                generated_at=newer_time,
                generated_by_email="op@finrlx.local",
            )
        )
        # Decoy: different ticker, must not match.
        db.add(
            TickerInsights(
                ticker="GOOG",
                summary_text="DECOY",
                quarters_covered=[],
                provider="gemini",
                model="gemini-2.5-flash",
                generated_at=newer_time,
                generated_by_email="op@finrlx.local",
            )
        )
        await db.commit()

    async with test_session_factory() as db:
        latest = (
            await db.execute(
                select(TickerInsights)
                .where(TickerInsights.ticker == "MSFT")
                .order_by(TickerInsights.generated_at.desc())
                .limit(1)
            )
        ).scalar_one()

    assert latest.summary_text == "NEWER"


@pytest.mark.asyncio
async def test_quarters_covered_accepts_empty_list():
    """Edge case: a ticker with no filings yet still gets a row
    (the prompt will tell the model "no filings available") so the
    column must accept an empty list."""
    from tests.conftest import test_session_factory

    async with test_session_factory() as db:
        row = TickerInsights(
            ticker="ZZZZ",
            summary_text="No filings available.",
            quarters_covered=[],
            provider="gemini",
            model="gemini-2.5-flash",
            generated_by_email="op@finrlx.local",
        )
        db.add(row)
        await db.commit()
        saved_id = row.id

    async with test_session_factory() as db:
        saved = (
            await db.execute(select(TickerInsights).where(TickerInsights.id == saved_id))
        ).scalar_one()

    assert saved.quarters_covered == []
