/**
 * LEAP S5/S7a — Simple Mode dossier rendering (ported from the pre-S1 slice's
 * suite, upgraded to the spec: the payload's raw stance vocabulary must map
 * to research language at the UI boundary — the old suite asserted the raw
 * word; this one asserts the mapping).
 */
import { render, screen, fireEvent } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

vi.mock("@/lib/analytics", () => ({ track: vi.fn() }));

import {
  DisclaimerStrip,
  SummaryBar,
  TournamentScoreboard,
  VerdictCards,
  type DossierPayload,
} from "@/components/simple/DossierView";

const CANDIDATE = {
  key: "sma_cross",
  name: "SMA(20/50) crossover",
  kind: "heuristic",
  train_sharpe: 0.9,
  val_sharpe: 0.7,
  divergence: 0.2,
  penalty: 0.3,
  score: 0.4,
};

const DOSSIER: DossierPayload = {
  ticker: "TEST",
  generated_at: "2026-07-06T00:00:00Z",
  config_version: "v-test",
  freshness: { latest_bar: "2026-07-03", bars: 500, news_source_available: true },
  summary: {
    latest_close: 123.45,
    stance: "hold", // raw engine vocabulary — must render as "neutral"
    composite_score: 0.1,
    avg_confidence: 0.6,
    regime: "uptrend",
    stance_kind: "research stance",
  },
  sections: {
    technical: {
      available: true,
      features: { rsi_14: 55.2, macd_hist_12_26_9: 0.12, drawdown_20d: -0.02 },
      regime: { label: "uptrend", detail: "", kind: "research overlay" },
      composite: { stance: "buy", composite_score: 0.4, avg_confidence: 0.6 },
    },
    news_sentiment: {
      available: true,
      note: null,
      counts: { positive: 3 },
      items_7d: [
        {
          date: "2026-07-01",
          title: "TEST expands capacity",
          sentiment: "positive",
          compound: 0.4,
          why_this_matters: "Capacity affects supply assumptions.",
          annotation_meta: {
            model: "fake:m",
            generated_at: "2026-07-06",
            freshness_stamp: "2026-07-01",
          },
        },
      ],
    },
    fundamentals: { available: false, note: "Fundamentals join later." },
    model_insight: {
      candidates: [CANDIDATE],
      winner: { ...CANDIDATE, rationale: "highest penalty-adjusted validation score" },
      rl: { status: "queued_for_research_run", note: "RL candidates train only in the isolated research environment." },
    },
  },
  price_series: [
    { date: "2026-07-02", close: 122.0 },
    { date: "2026-07-03", close: 123.45 },
  ],
  disclaimers: [
    "Research analysis, not investment advice.",
    "Past performance does not predict future results.",
  ],
};

describe("Simple Mode dossier", () => {
  it("maps raw stance vocabulary to research language (never renders it raw)", () => {
    render(<SummaryBar dossier={DOSSIER} />);
    const bar = screen.getByText(/stance:/);
    expect(bar.textContent).toContain("neutral");
    expect(document.body.textContent).not.toMatch(/\bhold\b/);
  });

  it("renders ticker, price, regime, and the freshness stamp", () => {
    render(<SummaryBar dossier={DOSSIER} />);
    expect(screen.getByText("TEST")).toBeTruthy();
    expect(screen.getByText("123.45")).toBeTruthy();
    expect(screen.getByText(/regime: uptrend/)).toBeTruthy();
    expect(screen.getByText(/Data through 2026-07-03/)).toBeTruthy();
  });

  it("renders all four verdict cards with honest degraded fundamentals", () => {
    render(<VerdictCards dossier={DOSSIER} />);
    for (const title of ["Technical", "News & sentiment", "Fundamentals", "Model insight"]) {
      expect(screen.getByText(title)).toBeTruthy();
    }
    expect(screen.getByText("Fundamentals join later.")).toBeTruthy();
    expect(screen.getByText(/Why it matters: Capacity affects supply/)).toBeTruthy();
    expect(screen.getByText(/Generated by fake:m/)).toBeTruthy();
  });

  it("explains the winner and opens the scoreboard with penalty column + verbatim RL note", () => {
    render(<TournamentScoreboard tournament={DOSSIER.sections.model_insight} />);
    expect(screen.getByText(/winner: SMA\(20\/50\) crossover/)).toBeTruthy();
    expect(screen.getByText(/overfitting penalties/)).toBeTruthy();
    fireEvent.click(screen.getByText("How this was chosen"));
    expect(screen.getByText("Penalty")).toBeTruthy();
    expect(screen.getByText(/isolated research environment/)).toBeTruthy();
  });

  it("always shows the research-not-advice disclaimers", () => {
    render(<DisclaimerStrip disclaimers={DOSSIER.disclaimers} />);
    expect(screen.getByText(/not investment advice/)).toBeTruthy();
  });
});

describe("Simple routes chrome (S7a fix regression lock)", () => {
  it("SimpleShell renders exactly one main, the Pro switch, and no sidebar chrome", async () => {
    const { SimpleShell } = await import("@/components/shell/SimpleShell");
    const { container } = render(
      <SimpleShell>
        <div>content</div>
      </SimpleShell>,
    );
    expect(container.querySelectorAll("main").length).toBe(1);
    expect(screen.getByTitle(/Pro mode/)).toBeTruthy();
    expect(container.querySelector("aside")).toBeNull();
    expect(container.querySelector('input[type="search"]')).toBeNull();
  });
});

describe("K1 empty-state doctrine — no dash-walls", () => {
  it("collapses an all-null signal set into one explanatory state", async () => {
    const { render, screen } = await import("@testing-library/react");
    const { VerdictCards } = await import("@/components/simple/DossierView");
    const dossier = structuredClone(DOSSIER);
    dossier.sections.technical.features = {
      return_5d: null, return_20d: null, return_60d: null,
      volatility_20d: null, drawdown_20d: null,
    };
    render(<VerdictCards dossier={dossier as never} />);
    const state = screen.getByTestId("signals-empty-state");
    expect(state.textContent).toContain("waiting on price history");
    expect(state.textContent).toContain("not an analysis result");
    // the doctrine: zero dash rows render
    expect(screen.queryAllByText("—").length).toBe(0);
    expect(screen.queryByText("All signals")).toBeNull();
  });

  it("partial data renders values plus honest per-row notes, never bare dashes", async () => {
    const { render, screen, fireEvent } = await import("@testing-library/react");
    const { VerdictCards } = await import("@/components/simple/DossierView");
    const dossier = structuredClone(DOSSIER);
    dossier.sections.technical.features = { return_5d: 0.0123, return_60d: null };
    render(<VerdictCards dossier={dossier as never} />);
    fireEvent.click(screen.getByText("All signals"));
    expect(screen.getByText("0.0123")).toBeTruthy();
    expect(screen.getByText("insufficient history")).toBeTruthy();
  });
});
