"use client";

import { usePaneContext } from "@/components/shell/ContextPane";

export function WarningsBlock({ warnings }: { warnings: string[] }) {
  const { openPane } = usePaneContext();

  if (warnings.length === 0) return null;

  return (
    <div className="p-qp-4 bg-qp-amber-400/10 border border-qp-amber-400 rounded-qp">
      <h3 className="text-qp-h3 text-qp-amber-600 mb-qp-2">
        {warnings.length} Warning{warnings.length > 1 ? "s" : ""}
      </h3>
      <ul className="space-y-qp-1">
        {warnings.map((w, i) => (
          <li
            key={i}
            className="text-qp-body text-qp-text-secondary cursor-pointer hover:text-qp-text-primary transition-colors duration-qp"
            onClick={() =>
              openPane("Warning Detail", (
                <div className="space-y-qp-3">
                  <p className="text-qp-body">{w}</p>
                  <p className="text-qp-small text-qp-text-muted">
                    This warning was generated by the risk overlay or governance layer.
                  </p>
                </div>
              ))
            }
          >
            &bull; {w}
          </li>
        ))}
      </ul>
    </div>
  );
}
