"use client";

import { Icon } from "@/components/icons/Icon";
import { usePaneContext } from "@/components/shell/ContextPane";

export function WarningsBlock({ warnings }: { warnings: string[] }) {
  const { openPane } = usePaneContext();

  if (warnings.length === 0) return null;

  return (
    <div className="rounded-lg border border-caution/30 bg-caution-soft p-pad">
      <h3 className="text-[13px] font-semibold text-caution-soft-ink mb-2">
        {warnings.length} Warning{warnings.length > 1 ? "s" : ""}
      </h3>
      <div className="space-y-1.5">
        {warnings.map((w, i) => (
          <div
            key={i}
            className="flex items-start gap-2 text-[12.5px] text-caution-soft-ink cursor-pointer hover:text-ink transition-colors"
            onClick={() =>
              openPane("Warning Detail", (
                <div className="space-y-3">
                  <div className="flex items-start gap-2 text-[13px]">
                    <Icon name="alert-triangle" size={14} className="text-caution mt-0.5 shrink-0" />
                    <p className="text-ink-2">{w}</p>
                  </div>
                  <p className="text-[11px] text-ink-4">
                    Generated by the risk overlay or governance layer.
                  </p>
                </div>
              ))
            }
          >
            <Icon name="alert-triangle" size={12} className="mt-0.5 shrink-0" />
            <span>{w}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
