"use client";

import { useEffect, useState } from "react";

/**
 * Blocking one-time disclaimer modal (Phase MVP-5).
 *
 * Shown on first visit until the user clicks "I understand". Acceptance is
 * persisted in localStorage so it does not interrupt the flow on subsequent
 * sessions. Versioned via DISCLAIMER_VERSION so we can force re-acceptance
 * after a legal-text change.
 *
 * Compliance notes:
 * - The modal is the FIRST interactive content on first visit. A reasonable
 *   tester cannot reach a Recommendation without seeing it.
 * - Persisting acceptance in localStorage (not a cookie) keeps it client-only
 *   and out of any server-logged headers. This is also why we do not gate
 *   server rendering on it.
 */

const STORAGE_KEY = "finrlx-disclaimer-accepted-v1";
const DISCLAIMER_VERSION = "v1";

export function DisclaimerModal() {
  // Start closed to avoid an SSR/CSR mismatch — open only after we've read
  // localStorage on the client.
  const [open, setOpen] = useState(false);

  useEffect(() => {
    try {
      const accepted = window.localStorage.getItem(STORAGE_KEY);
      if (accepted !== DISCLAIMER_VERSION) {
        setOpen(true);
      }
    } catch {
      // localStorage blocked (private mode, etc.). Show the modal every
      // visit — annoying but safer than silently skipping disclosure.
      setOpen(true);
    }
  }, []);

  if (!open) return null;

  const accept = () => {
    try {
      window.localStorage.setItem(STORAGE_KEY, DISCLAIMER_VERSION);
    } catch {
      // Ignore — we still close so the user can use the app this session.
    }
    setOpen(false);
  };

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="finrlx-disclaimer-title"
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-pad"
    >
      <div className="w-full max-w-md rounded-lg bg-canvas-elevated p-6 shadow-2xl">
        <h2 id="finrlx-disclaimer-title" className="mb-3 text-lg font-semibold">
          Before you continue
        </h2>
        <div className="space-y-3 text-sm text-text-default">
          <p>
            <strong>FINRLX is not a broker or financial advisor.</strong> The
            output you see is a decision-support signal generated by quantitative
            models on historical data. It is <em>not</em> investment advice and
            not a recommendation to buy, sell, or hold any security.
          </p>
          <p>
            Markets carry risk. Past performance does not predict future results.
            You are solely responsible for any investment decisions you make.
          </p>
          <p>
            By clicking <em>I understand</em> you confirm you have read the{" "}
            <a href="/disclaimer" className="underline">
              disclaimer
            </a>
            ,{" "}
            <a href="/terms" className="underline">
              terms of service
            </a>
            , and{" "}
            <a href="/privacy" className="underline">
              privacy policy
            </a>
            .
          </p>
        </div>
        <button
          type="button"
          onClick={accept}
          className="mt-5 w-full rounded-md bg-accent-default px-4 py-2 text-sm font-medium text-white hover:bg-accent-hover"
        >
          I understand
        </button>
      </div>
    </div>
  );
}
