/**
 * Persistent compliance banner (Phase MVP-5).
 *
 * Rendered once in the app shell footer and visible on every page that shows
 * Recommendation output. Required by the fintech-disclaimer-and-marketing-guard
 * skill: every Recommendation surface must include a disclaimer in its render
 * tree.
 *
 * Copy is intentionally plain so it reads on a phone and is parseable by
 * screen readers without extra ARIA wiring.
 */
export function DisclaimerBanner() {
  return (
    <footer
      data-disclaimer="true"
      role="contentinfo"
      className="border-t border-divider bg-canvas-elevated px-pad py-2 text-xs text-text-muted"
    >
      <span className="font-medium">Not investment advice.</span>{" "}
      FINRLX is a decision-support tool for educational research. Output is
      generated by models on historical data and is not a recommendation to buy
      or sell any security. See the{" "}
      <a href="/disclaimer" className="underline hover:text-text-default">
        full disclaimer
      </a>
      ,{" "}
      <a href="/terms" className="underline hover:text-text-default">
        terms
      </a>
      , and{" "}
      <a href="/privacy" className="underline hover:text-text-default">
        privacy
      </a>
      .
    </footer>
  );
}
